server:
  port: 8080
mail_server:
  server_address: smtp.gmail.com
  port: 465
  # TODO: Following to be stored as an Environment Variable in Docker
  email: xxxxx
  password: xxxxx
aws_rds:
  rds: url
  access_key_id: xxxx
  secret_access_key: xxxx
database:
  database_name :  cmpe295
  user_name : postgres
  password : root
  database_host : localhost
  database_port : 5432
  pool_size : 10
  pool_timeout : 30